### PR TITLE
Fix for #20.

### PR DESCRIPTION
**Pull request by wbyoung**
I don't know how to build this project, so I didn't test this at all, but I think this would work.

### CODE REVIEW

**Comment by MoOx** [comment]
Like most node project, `npm install && npm test` will install deps and run tests to ensure you didn't break anything.
Your fix is not bad, but I will not merge this. Instead I will push a fix covered by tests and release that as 1.0.1.

**Comment by wbyoung** [comment]
Ok, thanks.

**Comment by MoOx** [comment]
Closed by 4bd763f781466e024b4c3942f43c77d13182ad31

**Comment by MoOx** [comment]
Fix released as 1.0.1

**Comment by wbyoung** [comment]
Thanks!

**Pull request closed without merging**
