### PR TITLE
Replace Metalsmith.run method to Metalsmit.build in favour of pattern dirs

### PR DESCRIPTION
**Pull request by obetomuniz**

### CODE REVIEW

**Comment by FWeinb** [comment]
Will this result in a breaking change? Could you explain what the reason behind this change is. I did not have much time following the development of metalsmith.

**Comment by obetomuniz** [comment]
The use of `Metalsmith.build()` method allows for example to use patterns with sub-levels, for example: `../**/*` for general observation without aggression in project when we call the REBUILD. The `Metalsmith.run()` also allows the use of patterns with sub-levels, but especially when we are talking about templates.hbs and partials.hbs files it "generates" new folders and exposes a "bug" in metalsmith-watch.

Another point is the semantic meaning of methods, since the "BUILD" is to rebuild and RUN is to run without build.

What do you think of the proposed amendment?

**Comment by obetomuniz** [comment]
@FWeinb ping!

I'm using the fork of metalsmith-watch in this project: [Conf Boilerplate (Migration of Docpad2Metalsmith)](https://github.com/braziljs/conf-boilerplate/tree/migration/docpad2metalsmith).

**Comment by FWeinb** [comment]
Sounds like a good plan to me! Thanks for doing it.

**Comment by FWeinb** [comment]
Tests are breaking after merging this. I don't really know why, you might want to have a look.

**Comment by obetomuniz** [comment]
I do not understand, for me the tests are going well.

Take a look:
screen shot 2015-03-03 at 12 22 39 am

I'll check possible problems.

**Comment by obetomuniz** [comment]
In fact they work sometimes, not all the time.  ... Maybe a problem with the file writing time. I'll check this.

**Comment by obetomuniz** [comment]
If you prefer, you can return to the previous version of the project. Until I fix it. :smile:

**Comment by zenorocha** [comment]
Tests still broken.

**Pull request merged**
