### PR TITLE
1.0.0

### LINKED ISSUE #4: Watch multiple directories
It would be nice to have the option to watch several directories. My use case: I want to watch my src directory *and* my templates directory. For now, I have to include my templates in my src only so they can be watched, and they end up in the build directory, which is messy.

### LINKED ISSUE #13: Rebuild not starts if changes were done in included template file
If template has kind of "include/extends" directive, then watcher detects changes in included/extended file, but it doesn't make a rebuild. Example:

**index.jade:**
```jade
extends _base.jade

block someSpecificContent
	div Some specific content
```

**_base.jade:**
```jade
doctype html
html
	head
		title Any title
		script(src='http://localhost:35729/livereload.js')
	body
		block someSpecificContent
```

Run `node build.js`. Now modify `index.jade`, plugin detects changes, rebuilds and notifies browser. This is OK.

Then modify `_base.jade` –  plugin detects changes, but no rebuild/notification happens. This is NOT OK.

### PR DESCRIPTION
**Pull request by MoOx**
## Changes

- Fixed: metalsmith-collections are now correctly adjusted to avoid
duplicates entries after rebuilds)
- Removed: `pattern` option has been remove. Please use the new `paths`
option
- Added: `paths` option allows you to specify a map to trigger rebuilds
(closes [#4](https://github.com/FWeinb/metalsmith-watch/issues/4) and
[#13](https://github.com/FWeinb/metalsmith-watch/issues/13))
- Added: `log` option to be able to control watcher logs
- Added: when a JavaScript file is changed, the corresponding cache in
node/iojs cache is refreshed.
This is particularly handy when working with plain JavaScript template
(eg: react template made with
[metalsmith-react](https://github.com/MoOx/metalsmith-react))

## Technical changes

- source written using babel
- switch from jshint to eslint
- move changelog in it's own file
- add license
- added myself as an author
- use tape for test instead of mocha

Closes #4
Closes #13
Closes #17
Closes #18

### CODE REVIEW

**Comment by JoshConley** [comment]
Using the paths documented like this doesn't trigger a rebuild of everything:

```
'${source}/**/*': true
'partials/**/*': '**/*'
```
As you can see here:
```
[metalsmith-server] ✔︎ partials/header.html changed
[metalsmith-server] - Updating 0 file...
```

When using:
```
'${source}/**/*': true
'partials/**/*': true
```
...the partial rebuilds but the source doesn't, of course, so it doesn't update the source with the new partial.

Is this intended?  I'm trying to get the source to rebuild as well as the partial.

**Comment by MoOx** [comment]
[Recent metalsmith release](https://github.com/segmentio/metalsmith/issues/134#issuecomment-99023429) introduced a breaking change in run() method. So this branch is kind of broken.
That's why I didn't merge this. I have this fix this shit somehow...  :/

**Comment by MoOx** [comment]
Ok I said some shit previously my bad. This is supposed to work @JoshConley.
I will push more tests to be sure.

**Comment by JoshConley** [comment]
Thanks for the update!  Has something changed to make it work?

**Comment by MoOx** [comment]
No I didn't change anything for now, I was having local changes that make me think something was wrong.
Can you provide more informations on you setup so I can double check what is wrong ? (eg: folders structures, metalsmith dir, source, dest)

**Comment by JoshConley** [comment]
Yes!  Essentially, folders are structured like this:
- /src
- /partials

When the partials change, the watch script recognizes the file changed, but doesn't rebuild the source file.

Using this config:
```
'${source}/**/*': true
'partials/**/*': '**/*'
```

Again, I get the same as I commented above (partials/header.html changed, updating 0 files).  When the partial loads, the source should be rebuilt.  Same thing happens if I use `'partials/**/*': '${source}/**/*'`.  The source isn't rebuilding, it's only rebuilding changed files.

**Comment by MoOx** [comment]
I guess the / is considered to be your metalsmith root amarite ?
The weird part is "updating 0 files", at this stage the glob specified for `'partials/**/*'` (so this -> `'**/*'`) is used in the metalsmith.source folder (so /src). You should get the number of all your files in this folder.
Can you share more stuff like your all metalsmith build script ?

**Comment by JoshConley** [comment]
Yup!  I don't have access to it at the moment but I can share the build script with you tomorrow.  Thanks for your help.

**Comment by FWeinb** [comment]
Awesome! Work thank you so much for this! :fireworks:

**Comment by MoOx** [comment]
blink

**Pull request merged**
